### ISSUE TITLE
I don't see a post about LaadsDac_podaci data

### ISSUE THREAD

**Issue by cerenipoglu** [TesanovicNikola/Master_analysis#1]
Hello, 

It's a nice and explanatory work, but I don't see a post about the LaadsDac_podaci data in HDF5_creation.R. Can you share the data you used?

**Comment by TesanovicNikola** [comment]
Hello,

The data used for this was downloaded from:
https://ladsweb.modaps.eosdis.nasa.gov/archive/allData/5000/VNP46A3/2022
The entire year was used, but i only used data that was relevant for my case, or rather for my region. That data was h19v04 and h20v04.

**Comment by cerenipoglu** [comment]
Thank you. Good work :)
