### ISSUE TITLE
I can't coordinate

### ISSUE THREAD

**Issue by cerenipoglu** [TesanovicNikola/Master_analysis#2]
hello, I want to practice for night light and I'm trying to run your code for it. as in the code, I use the data h19v04 and h20v05 and run it. as a result, the data I record gives a new data that is the result of the overlap of these two data. therefore I cannot get the values of the two data. what can I do for this?

**Comment by TesanovicNikola** [comment]
So the point of the code is to filter out only data that are representing the night picture for my Country, that is Serbia. The script pulls out only the coordinates that are associated with my Country, and from those two files creates 1 file with all needed coordinates. After that the new file can be used with third party software to draw the map of the country.

**Comment by cerenipoglu** [comment]
Thank you for your answer. Yes I ran the code and from these two files it creates 1 file with all the necessary coordinates but my problem is that the new image is created by overlapping these two files. I don't understand what the error is caused by unfortunately.
